export const cities = [
    'Auckland',
    'Christchurch',
    'Wellington',
    'Hamilton',
    'Tauranga',
    'Dunedin',
    'Palmerston North',
    'Whangārei',
    'Nelson',
    'New Plymouth',
    'Hastings',
    'Rotorua',
    'Napier',
    'Invercargill',
    'Kāpiti Coast',
    'Gisborne',
    'Whanganui',
]
